import type { Metadata } from 'next';
import { ContactForm } from '../components/contact-form';
import { PageHero } from '../components/page-hero';
import { GoogleMapsIcon, InstagramIcon, LinkedInIcon, MailIcon, WhatsAppIcon } from '../components/social-icons';

export const metadata: Metadata = { title: 'Contacto', description: 'Solicita una asesoría en prevención de riesgos y seguridad laboral con ASSEL SpA.' };

export default function ContactoPage() {
  return <main className="inner-page contact-page"><PageHero index="06" eyebrow="Conversemos" title="Cuéntanos el desafío." accent="Diseñemos la respuesta." intro="Una conversación inicial puede ayudarnos a entender tu contexto, ordenar prioridades y recomendar el mejor siguiente paso." />
    <section className="contact-layout"><div className="contact-info"><p className="eyebrow dark"><span /> Contacto directo</p><h2>Estamos disponibles para escuchar.</h2><p>Escríbenos mediante el formulario o utiliza WhatsApp si necesitas una respuesta más directa.</p><div className="contact-options"><a href="https://wa.me/56971401031?text=Hola%20ASSEL%2C%20quiero%20solicitar%20una%20asesor%C3%ADa" target="_blank" rel="noopener noreferrer" aria-label="Conversar con ASSEL por WhatsApp al +56 9 7140 1031"><span className="whatsapp-contact-icon"><WhatsAppIcon /></span><p><small>WhatsApp</small><strong>+56 9 7140 1031</strong></p><b>↗</b></a><a href="mailto:contacto@assel.cl"><span className="email-contact-icon"><MailIcon /></span><p><small>Correo</small><strong>contacto@assel.cl</strong></p><b>↗</b></a><div><span className="google-maps-contact-icon"><GoogleMapsIcon /></span><p><small>Ubicación</small><strong>Santiago de Chile</strong></p></div><a href="https://www.linkedin.com/in/crist%C3%B3bal-vald%C3%A9s-85a6b81a5/" target="_blank" rel="noopener noreferrer" aria-label="Visitar el perfil de LinkedIn de Cristóbal Valdés"><span className="contact-social-icon linkedin"><LinkedInIcon /></span><p><small>LinkedIn</small><strong>Cristóbal Valdés</strong></p><b>↗</b></a><a href="https://www.instagram.com/assel_asesorias/" target="_blank" rel="noopener noreferrer" aria-label="Visitar el perfil de Instagram de ASSEL Asesorías"><span className="contact-social-icon instagram"><InstagramIcon /></span><p><small>Instagram</small><strong>@assel_asesorias</strong></p><b>↗</b></a></div><div className="contact-hours"><small>Horario de atención</small><p>Lunes a viernes<br /><b>09:00 — 18:00</b></p></div><p className="provisional-note">Los datos de contacto son provisorios y se reemplazarán antes de la publicación definitiva.</p></div><ContactForm /></section>
    <section className="contact-map"><div><span>SCL</span><p>Santiago de Chile</p><small>Cobertura presencial en la Región Metropolitana y acompañamiento a nivel nacional.</small></div></section>
  </main>;
}
