import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHero } from '../components/page-hero';

export const metadata: Metadata = { title: 'Nosotros', description: 'Conoce cómo ASSEL transforma la prevención, la seguridad y el bienestar en una inversión colaborativa de alto valor.' };

export default function NosotrosPage() {
  return <main className="inner-page"><PageHero index="02" eyebrow="Quiénes somos" title="Aliados presentes." accent="Valor que permanece." intro="Colaboramos con organizaciones de todos los tamaños para prevenir, gestionar y convertir la seguridad y el bienestar en una inversión que fortalece su negocio." image="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=2200&q=84" />
    <section className="about-story"><div className="about-lead"><p className="eyebrow dark"><span /> Nuestra convicción</p><h2>La prevención no es un costo que se cumple. Es una inversión que protege, ordena y hace avanzar el negocio.</h2></div><div className="about-copy"><p>En ASSEL no llegamos como un proveedor externo que entrega una solución y se retira. Nos incorporamos como colaboradores de confianza, entendiendo la operación, acompañando las decisiones y co-creando capacidades que permanecen.</p><p>Estamos junto a personas, microempresas, pymes y organizaciones globales para prevenir riesgos, gestionar obligaciones y agregar valor legal, operacional y humano a cada etapa de su crecimiento.</p><div className="signature"><span>AS</span><p><strong>Colaboración estratégica ASSEL</strong><small>Cercanía técnica · Gestión compartida · Valor sostenible</small></p></div></div></section>
    <section className="scale-band"><div><p className="eyebrow"><span /> Una solución para cada escala</p><h2>Desde una persona<br />hasta una operación global.</h2></div><div className="scale-track"><article><span>01</span><strong>Personas</strong><p>Orientación clara para profesionales y responsables de pequeñas operaciones.</p></article><article><span>02</span><strong>Micro y pequeñas empresas</strong><p>Bases preventivas simples, aplicables y preparadas para crecer.</p></article><article><span>03</span><strong>Pymes</strong><p>Gestión continua que ordena el cumplimiento y fortalece la operación.</p></article><article><span>04</span><strong>Empresas globales</strong><p>Gobernanza, trazabilidad y estándares consistentes entre sedes y equipos.</p></article></div></section>
    <section className="profile-section"><div className="profile-image"><img src="https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1400&q=82" alt="Profesional revisando documentación técnica" /><span>01 / Colaboración activa</span></div><div className="profile-content"><p className="eyebrow"><span /> Nuestra forma de trabajar</p><h2>No trabajamos para tu empresa. Trabajamos con ella.</h2><p>Combinamos criterio técnico, presencia en terreno y comunicación directa para convertir una exigencia compleja en decisiones comprensibles, controles utilizables y mejoras que el equipo puede sostener.</p><div className="credentials"><div><span>01</span><p><b>Prevenir</b><small>Anticipamos riesgos antes de que se transformen en incidentes, pérdidas o interrupciones.</small></p></div><div><span>02</span><p><b>Gestionar</b><small>Integramos obligaciones, procesos y evidencia en una gestión clara y trazable.</small></p></div><div><span>03</span><p><b>Agregar valor</b><small>Protegemos personas y continuidad mientras fortalecemos confianza, eficiencia y reputación.</small></p></div></div></div></section>
    <section className="commercial-strategy"><div className="strategy-heading"><p className="eyebrow dark"><span /> Estrategia comercial</p><h2>Solución Integral<br />de Entornos Seguros.</h2><p>Para una empresa B2B como ASSEL, el mayor reto no es la falta de interés: es cambiar la idea de que la seguridad y el bienestar son solamente un gasto obligatorio.</p></div><div className="strategy-body"><blockquote>Diseñamos una relación integral que resuelve problemas legales, operativos y humanos al mismo tiempo, demostrando que prevenir también produce retorno.</blockquote><div className="strategy-pillars"><article><span>01</span><h3>Valor legal</h3><p>Cumplimiento vigente, evidencia disponible y menor exposición a sanciones o contingencias.</p></article><article><span>02</span><h3>Valor operacional</h3><p>Menos interrupciones, controles aplicables y mejores decisiones para la continuidad del negocio.</p></article><article><span>03</span><h3>Valor humano</h3><p>Personas protegidas, equipos involucrados y una cultura basada en confianza y bienestar.</p></article></div></div></section>
    <section className="purpose-grid purpose-grid-official"><article className="purpose-card-featured"><small>01 / Propósito</small><h3>Actuar como aliados y colaboradores estratégicos de nuestros clientes, co-creando entornos seguros, éticos y confiables que transforman la seguridad y el bienestar en una inversión colaborativa de alto valor.</h3></article><article><small>02 / Misión</small><h3>Ser el aliado estratégico de nuestros clientes en la gestión de riesgos, co-creando culturas de trabajo seguras, éticas y saludables que potencien la eficiencia operacional, protejan a las personas y conviertan la prevención en una inversión de alto valor sostenible.</h3></article><article><small>03 / Visión</small><h3>Consolidarnos como referentes en el ámbito de la seguridad, la prevención y el bienestar laboral, reconocidos por transformar los entornos organizacionales en espacios de confianza, excelencia y alto rendimiento a través de la colaboración estratégica.</h3></article></section>
    <section className="inner-cta"><div><p className="eyebrow"><span /> Invirtamos en prevención</p><h2>Construyamos un entorno seguro que también haga crecer tu negocio.</h2><p>Partimos escuchando tu realidad y diseñamos una solución proporcional a tu tamaño, riesgos y objetivos.</p></div><Link className="button-primary" href="/contacto">Iniciar una conversación <span>→</span></Link></section>
  </main>;
}
