import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHero } from '../components/page-hero';

export const metadata: Metadata = { title: 'Nosotros', description: 'Conoce el enfoque técnico y humano de ASSEL para la prevención de riesgos laborales.' };

export default function NosotrosPage() {
  return <main className="inner-page"><PageHero index="02" eyebrow="Quiénes somos" title="Experiencia técnica." accent="Criterio humano." intro="Somos un equipo consultor que entiende la prevención como una capacidad de gestión: práctica, cercana y conectada con los objetivos de cada organización." image="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=2200&q=84" />
    <section className="about-story"><div className="about-lead"><p className="eyebrow dark"><span /> Nuestra convicción</p><h2>Una empresa segura no es la que nunca enfrenta riesgos. Es la que sabe reconocerlos y actuar a tiempo.</h2></div><div className="about-copy"><p>ASSEL nace para acompañar a organizaciones que necesitan convertir exigencias normativas y desafíos operacionales en una gestión preventiva que realmente funcione.</p><p>Combinamos experiencia en terreno, criterio técnico y comunicación clara. Nuestro trabajo comienza escuchando y termina cuando la solución puede sostenerse sin depender de nosotros.</p><div className="signature"><span>AS</span><p><strong>Profesional responsable</strong><small>Ingeniería en Prevención de Riesgos · Perfil provisorio</small></p></div></div></section>
    <section className="profile-section"><div className="profile-image"><img src="https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1400&q=82" alt="Profesional revisando documentación técnica" /><span>01 / Liderazgo técnico</span></div><div className="profile-content"><p className="eyebrow"><span /> Perfil profesional</p><h2>Conocimiento que se pone al servicio de las decisiones.</h2><p>El liderazgo técnico de ASSEL combina formación profesional, trabajo directo con equipos operativos y experiencia desarrollando sistemas de gestión para contextos diversos.</p><div className="credentials"><div><span>01</span><p><b>Formación profesional</b><small>Ingeniería en Prevención de Riesgos y actualización permanente.</small></p></div><div><span>02</span><p><b>Experiencia transversal</b><small>Servicios, logística, construcción, mantenimiento y proyectos.</small></p></div><div><span>03</span><p><b>Facilitación aplicada</b><small>Capacidad para traducir conceptos técnicos en acciones comprensibles.</small></p></div></div><small className="provisional-note">Los antecedentes, certificaciones y fotografía se reemplazarán por la información oficial de la empresa.</small></div></section>
    <section className="purpose-grid"><article><small>01 / Misión</small><h3>Hacer que la prevención sea clara, aplicable y parte natural de cada decisión de trabajo.</h3></article><article><small>02 / Visión</small><h3>Ser un socio técnico reconocido por transformar el cumplimiento en cultura y continuidad operacional.</h3></article><article className="values-card"><small>03 / Principios</small><ul><li>Criterio antes que burocracia</li><li>Evidencia antes que supuestos</li><li>Cercanía antes que distancia</li><li>Mejora antes que complacencia</li></ul></article></section>
    <section className="inner-cta"><div><p className="eyebrow"><span /> Trabajemos juntos</p><h2>Conoce cómo podemos fortalecer tu gestión preventiva.</h2></div><Link className="button-primary" href="/contacto">Solicitar una conversación <span>→</span></Link></section>
  </main>;
}
